name: 'Generate UML dependencies'
description: 'Generate UML'
branding:
  icon: bar-chart-2
  color: gray-dark
inputs:
  application-config-location:
    description: 'Application config location'
    required: true
  assembly-location:
    description: 'Assembly location'
    required: true
  assembly-config-location:
    description: 'Assembly config location'
    required: true
outputs:
  result:
    description: 'The UML'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.application-config-location }}
    - ${{ inputs.assembly-location }}
    - ${{ inputs.assembly-config-location }}
