name: Generate Diagrams

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1

    - name: Build project
      run: dotnet build -c Release

    - name: Generate a NuGet package
      run: dotnet run -p src/DepTree.Console --config applicationconfig.json -a ./src/DepTree/bin/Release/net5.0/DepTree.dll -i None

    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Generate diagrams'
